name: Deploy Release

on:
  push:
    tags:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-clojure-deps
        with:
          key-label: 'tests'
      - uses: jdx/mise-action@v2
        with:
          install_args: "babashka java clojure"
      - name: Run tests
        run: bb test

  deploy:
    runs-on: ubuntu-latest
    needs: [ tests ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-clojure-deps
        with:
          key-label: 'deploy'
      - uses: jdx/mise-action@v2
        with:
          install_args: "babashka java clojure"
      - name: Set Active Babashka Version using mise
        run: mise use -g babashka@1.3.186
      - name: Deploy Release
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: bb deploy-release
      - name: Check if tag exists
        id: check_tag
        run: |
          if gh release view "$TAG" --repo="$GITHUB_REPOSITORY" > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi
      - name: Publish GitHub Release
        if: env.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${TAG}" \
              --generate-notes
